#!/bin/sh

#
# Author: Thomas Palmer
# Purpose:  Validate Date string and ensure its not before the c-Class launch
#
OALAUNCH="061400002006 UTC +6"
OALAUNCHTS="`date -d "$OALAUNCH" +%s`"
#ENDOFUNIXEPOCH="123123592037"

DW_SUCCESS=0
DW_ERR_BAD_DATE_STR=2
DW_ERR_DATE_BEFORE_CCLASS_LAUNCH=3
DW_ERR_DATE_AFTER_UNIX_EPOCH=4
DW_ERR_BAD_OPTION=10
DW_ERR_OPTION_NUM=11


#### Unfornately, I dont know of a quick way to vary req'd arg cound.
#### So, for --1920, just send me some text. I wont use it.

if [ "$#" -ne "2" ]; then
	echo "dateWrapper [ --check | --set | --1920 ] [\"MMDDhhmm{{CC}YY} {TZ}\"] | something]"
	exit $DW_ERR_OPTION_NUM;
fi

#### BusyBox date always returns 1, no matter if date string is 
#### good or bad.  Use stdout output to gauge success

case $1 in
	--check | --set )
		NEWDATESTR=$2
		;;
	--1920) # Check today's date.  If bad, set to OA Launch
		./usr/sbin/dateWrapper --check `date +%m%d%H%M%Y`
		if [ $? = 0 ] ; then
			#echo "1920Check: Date is valid!  No Need to fix!"
			exit $?
		else
			echo "System Date is invalid!  Proceeding to fix."
		fi
		NEWDATESTR=$OALAUNCH
		;;
	*)
		echo "Invaid Option: $1"
		exit $DW_ERR_BAD_OPTION;
		;;
esac

DATERET="`date -d \"$NEWDATESTR\" +%s 2>/dev/null`"
DATESTR="`date -d \"$NEWDATESTR\" 2>/dev/null`"

#############################################################
#		Always validate input!!!
#############################################################
echo ""
echo -ne "Validating Date ... "

if [ $DATERET ] ; then
	echo -ne "Good Date String ... "
else
	echo "Bad Date String!!"
	exit $DW_ERR_BAD_DATE_STR
fi

if [ "$DATERET" -lt "$OALAUNCHTS" ] ; then
	echo "DateTime is before c-Class launch!"
	exit $DW_ERR_DATE_BEFORE_CCLASS_LAUNCH
fi


#if [ "$DATERET" -gt "$ENDOFUNIXEPOCH" ] ; then
#	echo "DateTime is after UNIX Epoch!"
#	echo $DATESTR
#	exit $DW_ERR_DATE_AFTER_UNIX_EPOCH
#fi

echo "Date is Valid!"
#############################################################



case $1 in
	--check) 
		#If we got here, then we checked out fine
		exit $DW_SUCCESS
		;;
	--1920)
		#Add this to the log
		logger -t OA "Illegal date! Correcting to June 14, 2006 for proper operation."
		;;
	--set)
		#Rely on libem to syslog appropriately
		;;
esac


#Set the time
echo -ne "Setting Date: "
date $NEWDATESTR
/usr/sbin/hwclock --systohc --utc



exit $DW_SUCCESS
