#!/bin/sh


COMMANDS=$*

for COMMAND in $COMMANDS
do
	PIDS=`ps -ea | grep $COMMAND | grep -v grep | sed "s/^ *//" | sed "s/ .*//"`

	for PID in $PIDS
	do
		echo "*******************"
		echo $COMMAND $PID
		echo "*******************"
		/usr/sbin/stack $PID 2> /dev/null
		cat /proc/$PID/maps 2> /dev/null
	done
done
