CFLAGS  = -I /home/marcelw/ia64/src/C/ssl/openssl/include/
CFLAGS += -I /home/marcelw/ia64/src/C/ssl/fips-2.0/include/ 

all:
	gcc $(CFLAGS) -Wall  -Wno-unused-variable -Wno-unused-but-set-variable -c x509.c

clean:
	rm *.o
